### PR TITLE
Add YY3568 support

### PR DESCRIPTION
**Pull request by efectn**

### CODE REVIEW

**Review by amazingfate — APPROVED** [review]

**Comment by igorpecovnik** [comment]
No need to rush anywhere with this. I still waiting reply from this vendor. If they don't even respond, there is no point dealing with them.

**Comment by amazingfate** [comment]
Ahh my bad. Let's wait to see how to deal with it.

**Comment by efectn** [comment]
> No need to rush anywhere with this. I still waiting reply from this vendor. If they don't even respond, there is no point dealing with them.

Then let me wait for build repo PR

**Comment by igorpecovnik** [comment]
> Then let me wait for build repo PR

Exactly. no worries.

**Pull request merged**
