### PR TITLE
Add init support for rock-5b and orangepi-5

### PR DESCRIPTION
**Pull request by amazingfate**
I'm going to delete these patches from https://github.com/armbian/build/tree/main/patch/kernel/rockchip-rk3588-legacy
| patch name | reason to delete |
| ---- | ---- |
| 2001-add-board-orangepi5.patch | already in this pull request |
| 2002-OrangePi5-Motorcomm-stuff-extracted-from-Xun.patch | upstream driver already backported to rkr3.6 |
| 2005-OrangePi5-tcpm-stuff-extracted-from-Xunlong-.patch | already applied to rkr3.6 |
| 2009-Variously-HDMI-improvements-for-OPi-5.patch | already in this pull request |
| 2010-Add-sata-support-on-Orange-Pi-5.patch | already in this pull request |
| 2011-Add-missing-I2C-SPI-PWM-UART-LCD-overlays-to-OrangePi5.patch | I only added board related lcd1 and lcd2, not all |
| 2012-Add-rockchip-rk3588-opp-oc-24ghz-overlay-for-RK3588.patch | already in this pull request |
| 2013-Disable-hardware-cursor-for-Rock-5B.patch | already in this pull request |
| 2014-Add-AP6275P-overlay-for-Orange-Pi-5.patch | I don't know if this is really needed by opi5, wifi card installed to m.2 m slot? |
| 999-remove-chosen-bootargs-from-dtsi.patch | already in this pull request |

### CODE REVIEW

**Comment by amazingfate** [comment]
@efectn take a look at our new kernel for rk3588, I hope it would work on orangepi 5

**Comment by rpardini** [comment]
excellent, I like the separate repo under armbian org. let's go ahead. we've until 23.05 to make it work.
I will personally only try to add the quartz64a which is what I have on hand until the end of March

**Review by rpardini — APPROVED** [review]

**Comment by rpardini** [comment]
suggestion: we could introduce a new BRANCH like `legacy-ng` (🤣 ) in armbian/build while we work stuff

**Comment by rpardini** [comment]
We also could use Tenkawa (dunno GH username) here for help woth the Khadas Edge2 when it comes to that

**Comment by amazingfate** [comment]
I will create a pull request to armbian/build, and provide testing images using github workflow based on my branch so that people can test this new kernel before the kernel change is merged. Let's merge this pr as a start.

**Comment by rpardini** [comment]
Oh ok great, go ahead!

**Comment by efectn** [comment]
Hi. Will try it tomorrow or Friday. Yeah we don't need overlay for ap6275p, it can be okay by default. I think it would be cool to add spi, pwm overlays to kernel. Or should they be added in armbian/build like other families?

**Pull request merged**
