### PR TITLE
Upgrade RKNPU driver to 0.9.6

### PR DESCRIPTION
**Pull request by Pelochus**
I was able to fix the issue https://github.com/armbian/linux-rockchip/issues/167 on my own. Tried to compile it, seems to work.

This driver version allows to run LLMs on RK3588 and similar chips. Check this out:
- https://github.com/airockchip/rknn-llm/tree/main
- https://www.reddit.com/r/RockchipNPU/comments/1c8176q/some_thoughts_on_the_rkllm_sdk/

### CODE REVIEW

**Comment by amazingfate** [comment]
Just extracting [rknpu_driver_0.9.6_20240322.tar.bz2](https://github.com/airockchip/rknn-llm/blob/main/rknpu-driver/rknpu_driver_0.9.6_20240322.tar.bz2) should work. Why there are so many commits?

**Comment by Pelochus** [comment]
You are right. I'm redoing that now.

**Comment by Pelochus** [comment]
Done :)

Anything else to do?

**Comment by amazingfate** [comment]
@Joshua-Riek any comments about this update?

**Comment by Joshua-Riek** [comment]
Looks good to me!

**Review by Joshua-Riek — APPROVED** [review]

**Pull request merged**
