### PR TITLE
Adding USB ports on Youyeetoo R1 v3

### PR DESCRIPTION
**Pull request by SuperKali**
Hi,

Today I received the board, but unfortunately, I encountered issues with the USB 3.0 ports. I spent some time figuring out how everything works, but even the vendor's version didn't have all the USB ports fully functional; some, like the USB 3.0 and USB 2.0 in its block, weren't working at all.

After testing, I was able to get all the USB ports detected correctly. Currently, there are 4 USB 2.0 ports and 1 USB 3.0 port working.

The board appears to be stable for now, but further updates will be made during the development period.

Thank you,  
Dany

### CODE REVIEW

**Comment by amazingfate** [comment]
Commit history is not readable, can you squash them?

**Comment by SuperKali** [comment]
@amazingfate now I don't know how to fix this conflict..

**Comment by amazingfate** [comment]
You are overwriting existing code.

**Comment by SuperKali** [comment]
@amazingfate how can fix?

**Comment by SuperKali** [comment]
@amazingfate i rollback the commit, but i didn't understand the squash, i'm so sorry :(

**Comment by SuperKali** [comment]
@amazingfate Now it's ok?

**Pull request merged**
