### PR TITLE
arm64: dts: audio fixes and 9tripod cleanup

### PR DESCRIPTION
**Pull request by Joshua-Riek**
Hello, I removed unused 9tripod device tree files and fixed a few sound issues for the opi5plus, nanopct6, and 9tripod devices.

### CODE REVIEW

**Comment by amazingfate** [comment]
What does this commit [arm64: dts: fix rockchip audio card names](https://github.com/armbian/linux-rockchip/pull/54/commits/29bf39870f4e2ce4c70300ec75b88612cb2f997e) fix?

**Comment by Joshua-Riek** [comment]
The commit 29bf39870f4e2ce4c70300ec75b88612cb2f997e will fix some of the current udev rules to differentiate audio output names. For example, the Orange Pi 5 Plus currently uses the below config for es8388, but it is incorrect.
```
SUBSYSTEM=="sound", ENV{ID_PATH}=="platform-es8388-sound", ENV{SOUND_DESCRIPTION}="ES8388 Audio"
```
This would be the appropriate udev rule.
```
SUBSYSTEM=="sound", ENV{ID_PATH}=="platform,es8388-sound", ENV{SOUND_DESCRIPTION}="ES8388 Audio"
```
This could easily be solved by updating the udev rule, but I think fixing it in the device tree makes more sense so there is no need to change the existing udev rules.

**Comment by amazingfate** [comment]
Here is the udev rule I use for dp sound on rock5b:
```
SUBSYSTEM=="sound", ENV{ID_PATH}=="platform-dp0-sound", ENV{SOUND_DESCRIPTION}="DP0 Audio"
```
There devicetree vaule:
```
$ cat /sys/firmware/devicetree/base/dp0-sound/rockchip,card-name
rockchip,dp0
```
The pulseaudio card info:
```
$ pacmd list-cards
4 card(s) available.
    index: 0
        name: <alsa_card.platform-dp0-sound>
        driver: <module-alsa-card.c>
        owner module: 7
        properties:
                alsa.card = "2"
                alsa.card_name = "rockchip,dp0"
                alsa.long_card_name = "rockchip,dp0"
                device.bus_path = "platform-dp0-sound"
                sysfs.path = "/devices/platform/dp0-sound/sound/card2"
                device.form_factor = "internal"
                device.description = "DP0 Audio"
                device.string = "2"
                module-udev-detect.discovered = "1"
                device.icon_name = "audio-card"
        profiles:
                output:stereo-fallback: Stereo Output (priority 5100, available: unknown)
                off: Off (priority 0, available: unknown)
        active profile: <output:stereo-fallback>
        sinks:
                alsa_output.platform-dp0-sound.stereo-fallback/#0: DP0 Audio
        sources:
                alsa_output.platform-dp0-sound.stereo-fallback.monitor/#0: Monitor of DP0 Audio
        ports:
                analog-output: Analog Output (priority 9900, latency offset 0 usec, available: unknown)
                        properties:
```

**Comment by Joshua-Riek** [comment]
I made a mistake there, I double-checked on my end and everything is working fine without the commit.
I will drop commit 29bf39870f4e2ce4c70300ec75b88612cb2f997e shortly, thanks!

**Review by amazingfate — APPROVED** [review]

**Pull request merged**
