### PR TITLE
Update RKNPU driver to 0.9.8

### PR DESCRIPTION
**Pull request by ghost**
Rockchip has [updated the RKNPU driver](https://github.com/airockchip/rknn-llm/blob/71773f050acf27261b05c076bf7e9a22f1bfb18c/rknpu-driver/rknpu_driver_0.9.8_20241009.tar.bz2).

### CODE REVIEW

**Comment by amazingfate** [comment]
Build failed:
```
  [🐳|🔨]   drivers/rknpu/rknpu_devfreq.c:237:25: error: 'rockchip_opp_set_low_length' undeclared here (not in a function)
  [🐳|🔨]     237 |         .set_soc_info = rockchip_opp_set_low_length,
  [🐳|🔨]         |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  [🐳|🔨]   make[4]: *** [scripts/Makefile.build:250: drivers/rknpu/rknpu_devfreq.o] Error 1
  [🐳|🔨]   make[3]: *** [scripts/Makefile.build:500: drivers/rknpu] Error 2
```

**Comment by ghost** [comment]
Sorry, I didn't check enough.

**Comment by Pelochus** [comment]
Any news on this update?

**Comment by amazingfate** [comment]
> Any news on this update?

rknpu kernel driver v0.9.8 depends on latest rkr4 kernel from sdk.
We are using rkr3 now.

**Comment by Pelochus** [comment]
Thanks for the quick response. Any plans on updating to rkr4 anytime soon?

**Comment by ghost** [comment]
@Pelochus 
For now, you can build the kernel by commenting out the line that causes the compile error.
As far as I have confirmed, it works fine with RK3588.
However, it may not work correctly with RK3576.

**Comment by Pelochus** [comment]
Cool thanks @thbd5000 !

**Pull request closed without merging**
