### PR TITLE
WIP: arch: arm64 board: youyeetoo r1 v3 add rewrited dts code.

### PR DESCRIPTION
**Pull request by SuperKali**
Hello everyone,

I’m working on integrating the DTS of this board into Armbian. Currently, I have one board available, but unfortunately, it has a manufacturing defect, which prevents me from testing the USB3 port. A replacement has already been sent, but considering the shipping times from China to Italy, I won’t receive it for another two weeks.

At the moment, the DTS is functioning correctly. Below is a list of tests I have already conducted:

## Currently Functioning:
 - 3x USB 2.0
 -  GPU & CPU
  - Boot from EMMC & SD
  - Audio and Video from HDMI
  - WIFI 6 PCIe Card
  - LCD DSI0/1 (Enabled by default 0)
  - AS8388 Driver (Headphones & Jack)
  - NFC Antenna
  - GPIO
 -  I2C
  - UART
## Currently Not Functioning:
  - 1x USB 3.0 (I can't test, my unit has a damaged chipset) – I’m waiting for the new unit
  - LCD DSI0/1 Touch not working properly (Maybe a OS problem)
  - Camera (To be integrated)

The specifications of the board are as follows:

| **Feature**       | **Description**                   |
|-------------------|-----------------------------------|
| **Model**         | Youyeetoo R1 V3                   |
| **CPU**           | RK3588S                           |
| **Memory**        | LPDDR4 (up to 32GB)               |
| **USB**           | 1x USB 3.0, 3x USB 2.0            |
| **Ethernet**      | 1x GbE                            |
| **I/O**           | GPIO, UART, NVME PCIe 2.0, eMMC, SD Card, M.2 (WiFi) |

I’ve tried forking the following repositories, builds, OS, and linux-rockchip, and have temporarily aligned the kernel from where to fetch, but I’m encountering an error during compilation. Any advice or help to assist me in integrating this board would be greatly appreciated.

I want to clarify that I’m still in the process of learning, so any suggestions are welcome.

Looking forward to your feedback.

### CODE REVIEW

**Comment by SuperKali** [comment]
This is the error log on the compile: https://paste.armbian.com/liqiqakuna

**Comment by SuperKali** [comment]
I tried to compile bullseye, and it works: https://paste.armbian.com/atepiyeqok, i think there's a problem to compile newer versions, someone can confirm?

**Comment by amazingfate** [comment]
> This is the error log on the compile: https://paste.armbian.com/liqiqakuna

The error is not kernel related. Pull latest armbian/build and try again.

**Comment by SuperKali** [comment]
> The error is not kernel related. Pull latest armbian/build and try again.

Hi, yes, the problem was related to the build problem, i pulled the latest version and i compiled all version, i tried server version: all version is available here: https://share.superkali.me/s/CsXEGJoKTDBbDzc

**Comment by SuperKali** [comment]
@amazingfate as https://github.com/armbian/build/pull/7108 that is merged can you merge this into the kernel, thank you :)

**Review by amazingfate — APPROVED** [review]

**Pull request merged**
