### PR TITLE
arm64: dts: Add missing overlays

### PR DESCRIPTION
**Pull request by efectn**
This PR adds missing overlays for Rock 5A, ROCK5B and Orange Pi 5

### CODE REVIEW

**Review by rpardini — APPROVED** [review]
I pulled this, builds OK, a few warnings here and there, I'd say merge.

**Comment by amazingfate** [comment]
What's the overlays starting with rk3588*? Do they work on other boards except rock5b?

**Comment by efectn** [comment]
> What's the overlays starting with rk3588*? Do they work on other boards except rock5b?

There are some common pwm, i2c and spi overlays. So i didn't rename them. Should i rename camera overlays of opi5, one wire overlays of rock5?

**Review by amazingfate — APPROVED** [review]
Let's just merge it.

**Pull request merged**
