### PR TITLE
arm64: dts: rockchip: Add Orange Pi 3B v2.1

### LINKED ISSUE #229: Wayland Cursor Invisible [drm:vop2_plane_atomic_check] *ERROR*
I have share detailed information on [armbian forums](https://forum.armbian.com/topic/44197-build-framework-patches-placement-for-orangepi-3b-v21/?do=findComment&comment=200197) but here is a concise stuff

My SBC is Opi3b v2.1 on `jammy` with `panfrost` enabled
Whether I install `ubuntu-desktop` or `armbian-gnome`; the cursor is invisible, however cursor works OK while logged in as `X-session` of Ubuntu meaning `wayland` is to blame. If you logged in KODI wayland session cursor works OK?? GDM3 has no cursor as well

When I move cursor while in wayland session, these errors keep repeating `journalctl -f`

```
Aug 26 20:41:02 orangepi3b gnome-shell[2921]: Failed to post KMS update: drmModeAtomicCommit: Invalid argument
Aug 26 20:41:02 orangepi3b kernel: [drm:vop2_plane_atomic_check] *ERROR* Unsupported linear format at Cluster0-win0
Aug 26 20:41:02 orangepi3b gnome-shell[2921]: Page flip discarded: drmModeAtomicCommit: Invalid argument
Aug 26 20:41:02 orangepi3b gnome-shell[2921]: Failed to post KMS update: drmModeAtomicCommit: Invalid argument
Aug 26 20:41:02 orangepi3b kernel: [drm:vop2_plane_atomic_check] *ERROR* Unsupported linear format at Cluster0-win0
Aug 26 20:41:02 orangepi3b gnome-shell[2921]: Page flip discarded: drmModeAtomicCommit: Invalid argument
Aug 26 20:41:02 orangepi3b gnome-shell[2921]: Failed to post KMS update: drmModeAtomicCommit: Invalid argument
Aug 26 20:41:02 orangepi3b kernel: [drm:vop2_plane_atomic_check] *ERROR* Unsupported linear format at Cluster0-win0
Aug 26 20:41:02 orangepi3b gnome-shell[2921]: Page flip discarded: drmModeAtomicCommit: Invalid argument
 
```
I strongly believe its some GNOME related error. Internet is full of this bug when people are using eGPUs. If anyone has any idea, please help

### PR DESCRIPTION
**Pull request by dust-7**
### Changes
- Add dts for Orange Pi 3B v2.1 ([dts source](https://github.com/orangepi-xunlong/linux-orangepi/blob/38dd4d9d9a1578f173912529bd587f63d7bd81e0/arch/arm64/boot/dts/rockchip/rk3566-orangepi-3b-v2.dts))
- Rename dtb filenames for v1.1 and v2.1 for compatibility with mainline u-boot. Now we can rely on u-boot to automatically select the appropriate dtb. ([u-boot reference](https://github.com/u-boot/u-boot/commit/a52099b4a2ae9e8cafc79268325249bcad308012#diff-1ca8d9ce95828f53150c73714c349fd38c171c4c3d51c2e606fea59a4358af84R13-R14))
- Keep old dtb filename for v1.1. Board config can be updated later on to switch to mainline u-boot. ([board config](https://github.com/armbian/build/blob/0bc5d27701286cca8a76820a0263b4d8a42b5b56/config/boards/orangepi3b.csc#L10))
- Fix following issues:
  - Unable to turn on bluetooth
  - The USB port that's directly below the USB 3.0 port not working
  - Unable to load GDM3 and Gnome (dmesg reports `[drm:vop2_plane_atomic_check] *ERROR* Unsupported linear format at Cluster0-win0`). This fixes #229.

### Testing steps taken
1. Update [board config file](https://github.com/armbian/build/blob/main/config/boards/orangepi3b.csc) to the following:
    <details>
    <summary>Expand</summary>

    ```properties
    # Rockchip RK3566 quad core 4/8GB RAM SoC WIFI/BT eMMC USB2 USB3 NVMe PCIe GbE HDMI SPI
    BOARD_NAME="orangepi3b"
    BOARDFAMILY="rk35xx"
    BOARD_MAINTAINER=""
    BOOTCONFIG="orangepi-3b-rk3566_defconfig"
    BOOT_SOC="rk3566"
    KERNEL_TARGET="vendor,edge"
    FULL_DESKTOP="yes"
    BOOT_LOGO="desktop"
    IMAGE_PARTITION_TABLE="gpt"
    BOOT_SCENARIO="spl-blobs"
    BOOT_SUPPORT_SPI="yes"
    BOOT_SPI_RKSPI_LOADER="yes"

    # Override family config for this board; let's avoid conditionals in family config.
    function post_family_config__orangepi3b_use_mainline_uboot() {
      display_alert "$BOARD" "mainline (Kwiboo's tree) u-boot overrides" "info"

      BOOTSOURCE="https://github.com/u-boot/u-boot.git"
      BOOTBRANCH="tag:v2024.10-rc3"
      BOOTPATCHDIR="v2024.10-orangepi3b" # empty

      BOOTDIR="u-boot-${BOARD}" # do not share u-boot directory

      BOOTDELAY=1 # Wait for UART interrupt to enter UMS/RockUSB mode etc
      UBOOT_TARGET_MAP="BL31=${RKBIN_DIR}/${BL31_BLOB} ROCKCHIP_TPL=${RKBIN_DIR}/${DDR_BLOB};;u-boot-rockchip.bin u-boot-rockchip-spi.bin u-boot.itb idbloader.img idbloader-spi.img"
      unset uboot_custom_postprocess write_uboot_platform write_uboot_platform_mtd # disable stuff from rockchip64_common; we're using binman here which does all the work already

      # Just use the binman-provided u-boot-rockchip.bin, which is ready-to-go
      function write_uboot_platform() {
        dd if=${1}/u-boot-rockchip.bin of=${2} bs=32k seek=1 conv=fsync
      }

      # Smarter/faster/better to-spi writer using flashcp (hopefully with --partition), using the binman-provided 'u-boot-rockchip-spi.bin'
      function write_uboot_platform_mtd() {
        declare -a extra_opts_flashcp=("--verbose")
        if flashcp -h | grep -q -e '--partition'; then
          echo "Confirmed flashcp supports --partition -- read and write only changed blocks." >&2
          extra_opts_flashcp+=("--partition")
        else
          echo "flashcp does not support --partition, will write full SPI flash blocks." >&2
        fi
        flashcp "${extra_opts_flashcp[@]}" "${1}/u-boot-rockchip-spi.bin" /dev/mtd0
      }

    }

    ```
    </details>

2. Build image with following:
    `./compile.sh build BOARD=orangepi3b BRANCH=vendor BUILD_DESKTOP=yes BUILD_MINIMAL=no DESKTOP_APPGROUPS_SELECTED= DESKTOP_ENVIRONMENT=gnome DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base KERNEL_CONFIGURE=no KERNEL_GIT=shallow RELEASE=jammy`

3. Features tested working:
    - Ethernet
    - Wifi
    - Bluetooth
    - 4x USB ports
    - Sound output via HDMI
    - [rockchip legacy multimedia packages ppa](https://launchpad.net/~liujianfeng1994/+archive/ubuntu/rockchip-multimedia)
      - Chromium with video decoding acceleration
      - Clapper with video acceleration

### CODE REVIEW

**Comment by amazingfate** [comment]
It's strange that workflow build did not produce `rk3566-orangepi-3b-v2.1.dtb` and `rk3566-orangepi-3b-v1.1.dtb`.

**Comment by dust-7** [comment]
Interesting. Could it be because dtb filename contains 2 periods? I see `px30-engicam-px30-core-edimm2.2.dtb` is also not created.

**Comment by dust-7** [comment]
Issue found:
https://github.com/armbian/build/blob/main/lib/tools/common/dt_makefile_patcher.py#L83

Armbian build's `dt_makefile_patcher.py` uses a regex to determine if a line in Makefile contains dtb. The regex does not accept any line with a period before `.dtb` as a valid dtb. Will raise an issue.

**Comment by rpardini** [comment]
As mentioned on the downstream bug.... _maybe_ don't use DTs with periods? I don't think any mainline (or vendor, before that DT) had dots in it.

**Comment by dust-7** [comment]
Mainline u-boot [requires these specific DTB filenames](https://github.com/u-boot/u-boot/commit/a52099b4a2ae9e8cafc79268325249bcad308012#diff-1ca8d9ce95828f53150c73714c349fd38c171c4c3d51c2e606fea59a4358af84R13-R14) in order to match the DTB to the board version.

> I don't think any mainline (or vendor, before that DT) had dots in it.

They exist though.

[Mainline kernel Makefile](https://github.com/torvalds/linux/blob/master/arch/arm64/boot/dts/rockchip/Makefile):
- px30-engicam-px30-core-edimm2.2.dtb
- rk3566-orangepi-3b-v1.1.dtb
- rk3566-orangepi-3b-v2.1.dtb
- rk3566-pinenote-v1.1.dtb
- rk3566-pinenote-v1.2.dtb
- rk3566-pinetab2-v0.1.dtb
- rk3566-pinetab2-v2.0.dtb

[Vendor Makefile](https://github.com/orangepi-xunlong/linux-orangepi/blob/orange-pi-5.10-rk35xx/arch/arm64/boot/dts/rockchip/Makefile):
- rk3566-orangepi-cm4-v1.4.dtb

**Comment by defencedog** [comment]
Big Thanks to @dust-7 @amazingfate for `v2.1` Previous month I have worked a lot on this board as we use in it chemical engineering experiments. There is also an audio issue with 3.5mm jack & microphone not detected. Though these hardware works in kernel6.6.4 as [mentioned here](https://github.com/defencedog/orangepi3b_v2.1/tree/main/MicroLinux_Armbian_Orangepi3b_jammy_edge_6.6.4)

Per my experience if the output of `aplay -l` is following audio  from 3.5mm jack **works**
```
**** List of PLAYBACK Hardware Devices ****
card 0: HDMI [HDMI], device 0: fe400000.i2s-i2s-hifi i2s-hifi-0 [fe400000.i2s-i2s-hifi i2s-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: RK809 [Analog RK809], device 0: fe410000.i2s-rk817-hifi rk817-hifi-0 [fe410000.i2s-rk817-hifi rk817-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

If this is the output you get 3.5mm **do not** work
```
card 0: rockchiprk809 [rockchip-rk809], device 0: dailink-multicodecs rk817-hifi-0 [dailink-multicodecs rk817-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: rockchiphdmi [rockchip,hdmi], device 0: fe400000.i2s-i2s-hifi i2s-hifi-0 [fe400000.i2s-i2s-hifi i2s-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

```

**Comment by defencedog** [comment]
[Gi-0n](https://github.com/Gi-0n) I cannot create v2.1 v1.1 `dtb` `https://paste.armbian.com/usixivukaq `

**Comment by dust-7** [comment]
I was also not able to get audio via 3.5mm jack to work. I have not been able to fix it so far.

**Comment by defencedog** [comment]
@dust-7 in this mainline release `img` included 3.5mm audio in & out **both** works
`https://github.com/defencedog/orangepi3b_v2.1/tree/main/MicroLinux_Armbian_Orangepi3b_jammy_edge_6.6.4`

**Comment by defencedog** [comment]
> It's strange that workflow build did not produce `rk3566-orangepi-3b-v2.1.dtb` and `rk3566-orangepi-3b-v1.1.dtb`.

@amazingfate Am still not able to generate these x2 `dtb` files
```
# added new dts 
# modified old dts 
# modified Make
cd ~/build/cache/sources/linux-kernel-worktree/6.1__rk35xx__arm64/arch/arm64/boot/dts/rockchip
wget https://github.com/armbian/linux-rockchip/raw/9b8d2a3c5d0a39303cca5c99ad7fd9545fcd8752/arch/arm64/boot/dts/rockchip/rk3566-orangepi-3b-v1.1.dts
wget https://raw.githubusercontent.com/armbian/linux-rockchip/9b8d2a3c5d0a39303cca5c99ad7fd9545fcd8752/arch/arm64/boot/dts/rockchip/rk3566-orangepi-3b-v2.1.dts
wget -N https://github.com/armbian/linux-rockchip/raw/9b8d2a3c5d0a39303cca5c99ad7fd9545fcd8752/arch/arm64/boot/dts/rockchip/rk3566-orangepi-3b.dts
wget -N https://raw.githubusercontent.com/armbian/linux-rockchip/9b8d2a3c5d0a39303cca5c99ad7fd9545fcd8752/arch/arm64/boot/dts/rockchip/Makefile

# modified regex of [dt_makefile_patcher.py](https://github.com/armbian/build/blob/main/lib/tools/common/dt_makefile_patcher.py#L83)

# modified [board-conf file](https://github.com/armbian/build/blob/main/config/boards/orangepi3b.csc) as instructed in first post

./compile.sh kernel-dtb BOARD=orangepi3b BRANCH=vendor KERNEL_GIT=shallow SYNC_CLOCK=no IGNORE_UPDATES=yes SHARE_LOG=yes  OFFLINE_WORK=yes
```
But still no dtb files `https://paste.armbian.com/decugakiye`

**Comment by amazingfate** [comment]
`Clean up dts` is not a meaningful commit message, please change it.

**Comment by dust-7** [comment]
Commits squashed.

**Review by amazingfate — APPROVED** [review]

**Comment by amazingfate** [comment]
> > It's strange that workflow build did not produce `rk3566-orangepi-3b-v2.1.dtb` and `rk3566-orangepi-3b-v1.1.dtb`.
> 
> @amazingfate Am still not able to generate these x2 `dtb` files
> 
> ```
> # added new dts 
> # modified old dts 
> # modified Make
> cd ~/build/cache/sources/linux-kernel-worktree/6.1__rk35xx__arm64/arch/arm64/boot/dts/rockchip
> wget https://github.com/armbian/linux-rockchip/raw/9b8d2a3c5d0a39303cca5c99ad7fd9545fcd8752/arch/arm64/boot/dts/rockchip/rk3566-orangepi-3b-v1.1.dts
> wget https://raw.githubusercontent.com/armbian/linux-rockchip/9b8d2a3c5d0a39303cca5c99ad7fd9545fcd8752/arch/arm64/boot/dts/rockchip/rk3566-orangepi-3b-v2.1.dts
> wget -N https://github.com/armbian/linux-rockchip/raw/9b8d2a3c5d0a39303cca5c99ad7fd9545fcd8752/arch/arm64/boot/dts/rockchip/rk3566-orangepi-3b.dts
> wget -N https://raw.githubusercontent.com/armbian/linux-rockchip/9b8d2a3c5d0a39303cca5c99ad7fd9545fcd8752/arch/arm64/boot/dts/rockchip/Makefile
> 
> # modified regex of [dt_makefile_patcher.py](https://github.com/armbian/build/blob/main/lib/tools/common/dt_makefile_patcher.py#L83)
> 
> # modified [board-conf file](https://github.com/armbian/build/blob/main/config/boards/orangepi3b.csc) as instructed in first post
> 
> ./compile.sh kernel-dtb BOARD=orangepi3b BRANCH=vendor KERNEL_GIT=shallow SYNC_CLOCK=no IGNORE_UPDATES=yes SHARE_LOG=yes  OFFLINE_WORK=yes
> ```
> 
> But still no dtb files `https://paste.armbian.com/decugakiye`

Workflow of this pr doesn't have this issue. Make sure you have the latest code of armbian.

**Comment by defencedog** [comment]
@amazingfate **Generally** speaking lets suppose I have a new `xx.dts` file of an xx SBC how can I compile it. Per the documentation
```
cd ~/build/patch/kernel/rk35xx-vendor-6.1
cat 0000.patching_config.yaml
```
> .dts files in these directories will be copied as-is to the build tree; later ones overwrite earlier ones.
> This is meant to provide a way to "add a board DTS" without having to null-patch them in.

So I placed the new `xx.dts` file in this location but it didn't created `dtb` ?

**Comment by amazingfate** [comment]
> @amazingfate **Generally** speaking lets suppose I have a new `xx.dts` file of an xx SBC how can I compile it. Per the documentation
> ```
> cd ~/build/patch/kernel/rk35xx-vendor-6.1
> cat 0000.patching_config.yaml
> ```
> > .dts files in these directories will be copied as-is to the build tree; later ones overwrite earlier ones.
> > This is meant to provide a way to "add a board DTS" without having to null-patch them in.
> 
> So I placed the new `xx.dts` file in this location but it didn't created `dtb` ?

You have to put the dts file at dt dir.

**Comment by defencedog** [comment]
@amazingfate my [0000.patching_config.yaml](https://github.com/rpardini/armbian-build/blob/extensions/patch/kernel/archive/rk322x-6.1/0000.patching_config.yaml)
```
config:

  # Just some info stuff; not used by the patching scripts
  name: rk35xx-6.1
  kind: kernel
  type: vendor # or: vendor
  branch: rk-6.1-rkr3
  last-known-good-tag: v6.1.75

  # .dts files in these directories will be copied as-is to the build tree; later ones overwrite earlier ones.
  # This is meant to provide a way to "add a board DTS" without having to null-patch them in.
  dts-directories:
    - { source: "dt", target: "arch/arm64/boot/dts/rockchip" }

  overlay-directories:
    - { source: "overlay", target: "arch/arm/boot/dts/rockchip/overlay" }

  # the Makefile in each of these directories will be magically patched to include the dts files copied
  #  or patched-in; overlay subdir will be included "-y" if it exists.
  # No more Makefile patching needed, yay!
  # "incremental: true" changes the logic of the Makefile re-writing to only add the
  #                     dts-directories's *.dts files to existing Makefile instead of
  #                     full rewrite from *.dts in the dt dir at the end of patching.
  auto-patch-dt-makefile:
    - { incremental: yes, directory: "arch/arm64/boot/dts/rockchip", config-var: "CONFIG_ARCH_ROCKCHIP" }

  # configuration for when applying patches to git / auto-rewriting patches (development cycle helpers)
  patches-to-git:
    do-not-commit-files:
      - "MAINTAINERS" # constant churn, drop them. sorry.
      - "Documentation/devicetree/bindings/arm/rockchip.yaml" # constant churn, conflicts on every bump, drop it. sorry.
    do-not-commit-regexes: # Python-style regexes
      - "^arch/([a-zA-Z0-9]+)/boot/dts/([a-zA-Z0-9]+)/Makefile$" # ignore DT Makefile patches, we've an auto-patcher now
```

then file locations
```
:~/build/patch/kernel/rk35xx-vendor-6.1/overlay$ ls
Makefile                  rk356x-edp.dts  rk356x-i2c2-m1.dts  rk356x-i2c4-m0.dts    rk356x-ov5647-c2.dts  rk356x-pwm15-m1.dts  rk356x-spi3-m0-cs0-spidev.dts  rk356x-uart7-m2.dts
README.rockchip-overlays  rk356x-gpu.dts  rk356x-i2c3-m0.dts  rk356x-ov5647-c1.dts  rk356x-pwm11-m1.dts   rk356x-pwm7.dts      rk356x-uart3-m0.dts            rk356x-uart9-m2.dts
```

contents of Makefile in overlay folder
```
# SPDX-License-Identifier: GPL-2.0
dtbo-$(CONFIG_ARCH_ROCKCHIP) += \
        rk356x-uart9-m2.dtbo\
        rk356x-uart7-m2.dtbo\
        rk356x-uart3-m0.dtbo\
        rk356x-i2c2-m1.dtbo\
        rk356x-i2c3-m0.dtbo\
        rk356x-i2c4-m0.dtbo\
        rk356x-pwm11-m1.dtbo\
        rk356x-pwm15-m1.dtbo\
        rk356x-spi3-m0-cs0-spidev.dtbo\
        rk356x-gpu.dtbo


dtbotxt-$(CONFIG_ARCH_ROCKCHIP) += \
        README.rockchip-overlays

targets += $(dtbo-y) $(dtbotxt-y)

always         := $(dtbo-y) $(dtbotxt-y)
clean-files    := *.dtbo

```

Per the progress overlay files are added to correct location  but `dtbo` not generated https://paste.armbian.com/zupigobeyi This is verified by `dpkg --contents xx.deb`

**Comment by lopirata** [comment]
Compiled from sources, vendor kernel, v2.1.dtb generated, OK, but system hangs on boot anyway.
Compiled from sources, edge kernel, v2.1.dtb not generated.
Stuck here, can anyone help?

**Comment by amazingfate** [comment]
> Compiled from sources, vendor kernel, v2.1.dtb generated, OK, but system hangs on boot anyway. Compiled from sources, edge kernel, v2.1.dtb not generated. Stuck here, can anyone help?

You may try my commit to update uboot: https://github.com/armbian/build/pull/7025/commits/76122197b554fa9c62b74cf4b11a0d7371942355

**Comment by dust-7** [comment]
@lopirata for vendor kernel for v2.1 board, you'll have to manually update the board config file for now.  See step 1 of **Testing steps taken** in the first comment.

For edge kernel, you'll have to wait for kernel v6.11 to drop.

@amazingfate v2.1 board works with or without the uboot patch from Kwiboo.

**Comment by amazingfate** [comment]
> @amazingfate v2.1 board works with or without the uboot patch from Kwiboo.

I'm going to use mainline uboot, not Kwiboo's branch.

**Comment by defencedog** [comment]
> Compiled from sources, vendor kernel, v2.1.dtb generated, OK, but system hangs on boot anyway. Compiled from sources, edge kernel, v2.1.dtb not generated. Stuck here, can anyone help?

I generated `img` & related `debs` from updated board config file However the u-boot was unable to automatically identify board `v2.1` 

Note to @dust-7 I have to manually add `fdt-file` parameter in `armbianEnv.txt`

After this my BT started working...

**Comment by dust-7** [comment]
I just did a test and it works for me:
1. Deleted and cloned a fresh copy of Armbian build.
2. Updated board config to that in first comment.
3. `./compile.sh build BOARD=orangepi3b BRANCH=vendor BUILD_DESKTOP=no BUILD_MINIMAL=yes KERNEL_CONFIGURE=no KERNEL_GIT=shallow RELEASE=noble`
4. Image loads to terminal.
5. `cat /proc/device-tree/serial@fe650000/bluetooth/compatible` shows `brcm,bcm4345c5`, indicating v2.1 dts.

@defencedog I suspect you did not update your u-boot. Suggest you build and flash a complete image.

**Comment by defencedog** [comment]
@dust-7 thanks I will try & report back.

Also can you help me with [overlay](https://github.com/armbian/linux-rockchip/pull/234#issuecomment-2344814671) addition

**Comment by lopirata** [comment]
@dust-7 did that, booted, but no ethernet. So I did what @defencedog done editing fdt-file parameter in armbianEnv.txt
and ethernet is working! Although ethernet orange led isn't working, I got gigabit speed in tests.
Now I'm installing OMV and NextCloud to do some other tests.

For all there, I have two boards, one just to test stuff. If I can help with testing, just send me what to do.
I have some experience with Linux, but some dificulties to compile somethings (like u-boot).

PS: Thank you ALL, since end of june trying to make armbian work in this board and FINALLY!

EDIT: MAC address changes every reboot.
nmcli doesn't show end1, any hint in how solve it?

**Comment by defencedog** [comment]
> PS: Thank you ALL, since end of june trying to make armbian work in this board and FINALLY!

@lopirata I have an `img` with kernel 6.6 mainline. It provides maximum HW compatibility including sound devices like 3.5mm audio / microphone as well as all official overlays. The only HW not working is NPU ...Secondly VPU acceleration not includes H265 only H264

https://github.com/defencedog/orangepi3b_v2.1/tree/main/MicroLinux_Armbian_Orangepi3b_jammy_edge_6.6.4

**Comment by lopirata** [comment]
> > PS: Thank you ALL, since end of june trying to make armbian work in this board and FINALLY!
> 
> @lopirata I have an `img` with kernel 6.6 mainline. It provides maximum HW compatibility including sound devices like 3.5mm audio / microphone as well as all official overlays. The only HW not working is NPU ...Secondly VPU acceleration not includes H265 only H264
> 
> https://github.com/defencedog/orangepi3b_v2.1/tree/main/MicroLinux_Armbian_Orangepi3b_jammy_edge_6.6.4

Thank You!
Will try on the test board.

For the main board I need Armbian in Debian flavour to install OMV and Jellyfin. Will test HW acceleration too.

**Comment by defencedog** [comment]
@lopirata I believe for such stuff DietPi is OK ...

Also I am waiting for ethernet speeds

**Comment by igorpecovnik** [comment]
> I believe for such stuff DietPi is OK ...

I know Armbian or Debian OMV solution is better - no proprietary script bloatware, its pure, no additional security issues. As soon as you install OMV, "minimalism" and "optimisations" are gone as OMV is pretty bulky software bundle. BTW. Dietpi main self promo article [is just a bundle of lies](https://dietpi.com/stats.html) to support their believes.

I see they expanded their illusions with another fat lie: "_We maintain own kernel sources_", "and otherwise rely on and benefit from kernel development done by other projects". And they don't name other projects and they don't show how they maintain kernel sources ...

**Comment by lopirata** [comment]
@defencedog I've tried to install OMV and the things gone wrong, so, maybe tomorrow I'll do everything again, use Iperf and show some stuff here.

@igorpecovnik I'm usinge Armbian since 2017 on an Orange Pi Plus 2E, and I remember you in the forum teaching how to compile Armbian with OMV. Love the way OMV is easy to configure in Armbian and the interface itself, so easy to me to share files and media with my family.
About DietPi, I've never been able to use it, the menus are so confuse and the system just cracks up when I do something not scripted by it.

**Comment by defencedog** [comment]
@lopirata how are your ethernet results?

**Comment by lopirata** [comment]
> @lopirata how are your ethernet results?

root@orangepi3b:~# iperf3 -c 192.168.88.101
Connecting to host 192.168.88.101, port 5201
[  5] local 192.168.88.165 port 36994 connected to 192.168.88.101 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec   109 MBytes   914 Mbits/sec    0    450 KBytes       
[  5]   1.00-2.00   sec   113 MBytes   944 Mbits/sec    0    450 KBytes       
[  5]   2.00-3.00   sec   111 MBytes   935 Mbits/sec    0    450 KBytes       
[  5]   3.00-4.00   sec   113 MBytes   945 Mbits/sec    0    450 KBytes       
[  5]   4.00-5.00   sec   113 MBytes   944 Mbits/sec    0    450 KBytes       
[  5]   5.00-6.00   sec   112 MBytes   937 Mbits/sec    0    450 KBytes       
[  5]   6.00-7.00   sec   113 MBytes   946 Mbits/sec    0    469 KBytes       
[  5]   7.00-8.00   sec   112 MBytes   937 Mbits/sec    0    469 KBytes       
[  5]   8.00-9.00   sec   113 MBytes   945 Mbits/sec    0    469 KBytes       
[  5]   9.00-10.00  sec   112 MBytes   937 Mbits/sec    0    469 KBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  1.09 GBytes   938 Mbits/sec    0             sender
[  5]   0.00-10.00  sec  1.09 GBytes   937 Mbits/sec                  receiver


OMV still kill ethernet and MAC address keeps changing every reboot.
Found this searching for solutions:
https://forum.radxa.com/t/random-mac-address-after-reboot-with-spi-flash-and-nvme/8512

Still trying to realize how to apply this to opi3b.

**Comment by lopirata** [comment]
As I said early, the random MAC is a SPI issue as I'm booting from NVMe.

The solution is very simple, but not so fast: 

1-Flash a microSD card with the IMG, edit armbianEnv.txt properly to boot your specific board (in my case, v2.1);
2-After boot, configure Armbian and run armbian-config (or install, if you,re using minimal image);
3-On armbian-config select System, then Install, choose Boot From MTD Flash - System on SATA, USB or NVMe and confirm everything, wait patiently the file copy. When the copy ends, select Yes to write de bootloader to MTD Flash, confirm and wait the copy end.
4-Power off the board, remove the microSD card and boot from NVMe, check if the MAC has changed.

After that, reinstalled OMV and everything is fine.

Next steps:
Jellyfin server with HW acceleration decoding;
NextCloud server;
PiHole + PiVPN server.

**Comment by defencedog** [comment]
@lopirata kindly do me a favour. Please run `alsa-info` & attach the `.txt` file here I want to troublshoot missing audio from 3.5mm jack The utility will collect all relevant information ...

**Comment by lopirata** [comment]
> @lopirata kindly do me a favour. Please run `alsa-info` & attach the `.txt` file here I want to troublshoot missing audio from 3.5mm jack The utility will collect all relevant information ...

https://pastebin.com/sdNJXkQy

**Comment by defencedog** [comment]
@lopirata You are needed [here](https://github.com/armbian/build/pull/7233#issuecomment-2351491424)

**Pull request merged**
