### PR TITLE
Fix dp sound and cursor flicker

### PR DESCRIPTION
**Pull request by Joshua-Riek**
Hello again, I have a couple more minor fixes!
- 7332d78ed3ad8ac990b6121dd5d3e344d1a4ecb7 will fix audio through the display port 
- 2b70fb9cab3752472f24681f985041c4b05da2dd will fix the cursor flickering when using the display port and x11

### CODE REVIEW

**Review by amazingfate — DISMISSED** [review]

**Comment by Joshua-Riek** [comment]
My patch to fix the dp cursor flickering introduced an issue where wayland would crash on HDMI or DP hotplug, so I dropped the commit. 

I do, however, have a new commit for the opi5 that will fix a different issue, dp0 should be in vp2, not vp1.

**Comment by amazingfate** [comment]
@igorpecovnik this workflow has passed building but failed to upload to ghcr.

**Review by amazingfate — APPROVED** [review]

**Comment by igorpecovnik** [comment]
Yes, noticed. Have to figure out how to disable this ...

**Comment by igorpecovnik** [comment]
> his workflow has passed building but failed to upload to ghcr.

Fixed.

**Pull request merged**
