### PR TITLE
rebase commits from rk-6.1-rk1 to rk-6.1-rkr3

### PR DESCRIPTION
**Pull request by amazingfate**
Dropped commits:
| commit | drop reason |
| --- | --- |
| [drm/rockchip: vop2: remove WARN_ON for drm_modeset_is_locked](https://github.com/armbian/linux-rockchip/commit/19edaea16b063842a90d681a203340b2d619ed0c) | rockchip has reworked vop2 driver, ~~need to check if this patch is still necessary~~this WARN_ON is removed in rkr3 |
| [gpu: drm: rockchip: suppress unsupported format](https://github.com/armbian/linux-rockchip/commit/ba50d72c9216d0cd2ad28754d61e56929692f014) | rockchip has reworked vop2 driver ~~,need to check if this patch is still necessary~~. Rkr3 adds a new condition `!rockchip_rfbc(plane, modifier)` to this ERROR log, and I haven't see it after boot. The error log will print plane name, so I think it should be okay to keep this. |
| [video: rockchip: rga3: fix 4:2:2 10-bit reading in rga2](https://github.com/armbian/linux-rockchip/commit/a4f15ee8e53337d97973589f3634fe876557c54c) | rockchip has reworked rga2 driver and added 444 support, but 422 is also dropped, this patch is already reworked by @nyanmisaka |
| [driver: rknpu: Update rknpu driver, version: 0.9.4](https://github.com/armbian/linux-rockchip/commit/ba25544718f5c10369a83c7b02fec001a6f6e661) | rknpu has been update to 0.9.7 |
| [driver: rknpu: Update rknpu driver, version: 0.9.5](https://github.com/armbian/linux-rockchip/commit/ad74c2e7d5ba7f7c4188cd201094af9c3fba4c55) | rknpu has been update to 0.9.7 |
| [Updated drivers/rknpu to 0.9.6](https://github.com/armbian/linux-rockchip/commit/4145a7bad2b9e44628c37a137eb1c74789f5a35f) | rknpu has been update to 0.9.7 |
| [version_compat_defs: Add vm_flags_set()/vm_flags_clear()](https://github.com/armbian/linux-rockchip/commit/f3fb30ac9de06b41fb621d17bc53603f1f48ac90) | rkr3 already has this commit |
| [Avoid EPROBE_DEFER loop with Rockchip DSI driver](https://github.com/armbian/linux-rockchip/commit/f85a2f1fda1db5d3da53e1b25eef51f2081452c4) | rockchip has reworked dsi driver and we need to check if patch is still necessary. @ginkage has confirmed that rockchip has exactly the same fix: https://github.com/armbian/linux-rockchip/commit/d420d65bec8435e3e1198fbb7aaf3af04d10111b |

I just made these patches applied, ~~have not built this kenel yet~~kernel boots fine.

### CODE REVIEW

**Comment by nyanmisaka** [comment]
`video: rockchip: rga3: fix 4:2:2 10-bit reading in rga2`
They relocate the code and the patch needs to be slightly modified to fit. See https://github.com/Joshua-Riek/linux-rockchip/commit/f3e09e2dc2fbe77c7bb8d19fe1cf148f0d33725d

**Comment by ginkage** [comment]
Re: "rockchip has reworked dsi driver and we need to check if patch is still necessary" for https://github.com/armbian/linux-rockchip/commit/f85a2f1fda1db5d3da53e1b25eef51f2081452c4
Looks like they've applied almost exactly the same patch: https://github.com/armbian/linux-rockchip/commit/d420d65bec8435e3e1198fbb7aaf3af04d10111b

On a related note, where did the rkr3 branch come from? I can't see it in Jeffy's mirrors.

**Comment by amazingfate** [comment]
> Re: "rockchip has reworked dsi driver and we need to check if patch is still necessary" for [f85a2f1](https://github.com/armbian/linux-rockchip/commit/f85a2f1fda1db5d3da53e1b25eef51f2081452c4) Looks like they've applied almost exactly the same patch: [d420d65](https://github.com/armbian/linux-rockchip/commit/d420d65bec8435e3e1198fbb7aaf3af04d10111b)

Good to hear, so we can just drop this commit.

> 
> On a related note, where did the rkr3 branch come from? I can't see it in Jeffy's mirrors.

Rockchip just released new sdk with kernel tag rkr3 to their customers several days ago. Jeffy doesn't have much permission to upload such new kernel version.

**Comment by Joshua-Riek** [comment]
Whoops, I accidentally marked it as ready for review, ignore that lol.

**Comment by Joshua-Riek** [comment]
Hey @amazingfate, I found a bug where max user processes and pending signals where very low on the 6.1 rkr3 kernel, causing some users to experience a number of issues preventing new processes to be started when there is ample resources available on the system. 

I did some bisecting and was able to hunt down the problematic commits; https://github.com/armbian/linux-rockchip/commit/286ef81333ac174b65984c358e0cde32705536cc and https://github.com/armbian/linux-rockchip/commit/8ca3ffc967acded5184a1f4338f32aedaafef5e1, I recommend they be reverted. I'm very curious about commit https://github.com/armbian/linux-rockchip/commit/286ef81333ac174b65984c358e0cde32705536cc as to why it caused the problem, but this is something I will research another day.

Additional Info: https://github.com/Joshua-Riek/ubuntu-rockchip/issues/919

**Comment by amazingfate** [comment]
@Joshua-Riek Do you have `CONFIG_ROCKCHIP_THUNDER_BOOT` or `CONFIG_ROCKCHIP_THUNDER_BOOT_DEFER_FREE_MEMBLOCK` enabled? That two commits are related to these two kernel config.

**Comment by Joshua-Riek** [comment]
I had `CONFIG_ROCKCHIP_THUNDER_BOOT_DEFER_FREE_MEMBLOCK=y` in the kernel config when I encountered this issue. But now you point it out, it may be better to ensure both `CONFIG_ROCKCHIP_THUNDER_BOOT_DEFER_FREE_MEMBLOCK` and `CONFIG_ROCKCHIP_THUNDER_BOOT` are disabled, so there is no need to revert any commits.

**Comment by amazingfate** [comment]
Tested with rk3568 board hinlink-h66k and rk3528 board hinlink-ht2 and rk3588 board rock-5b, working fine.

**Comment by rpardini** [comment]
Tested on Mekotronics R58X (`-4G`, but `-Pro` and others should be the same). Seems to work fine. Tested the 2 gmac eths, wifi, wwan (which is USB2), USB3, USB-C's UDC, DisplayPort, nvme.

For reference, complete ANSI dmesg across kernels on this board.
- `5.10-rkr6`: https://paste.next.armbian.com/libubatise
- `6.1-rkr1`: https://paste.next.armbian.com/execapiloy
- this PR `6.1-rkr3-wip`: https://paste.next.armbian.com/yotuhapuca

**Comment by rpardini** [comment]
Also tested on Meko R58X-Pro with Panthor and KDE-Neon. Works fine.

**Comment by rpardini** [comment]
Tested on the Mixtile-Blade3, including SATA (via overlay), 4-pin fan, nvme, 2x 2.5gbit eth.

dmesg:
- 5.10-rkr6: https://paste.next.armbian.com/ejohehemov
- didn't get the chance to test rkr1 on this board, ever, unfortunately
- this PR 6.1-rkr3: https://paste.next.armbian.com/luyiraveta

With rkr3, seems like there's some dmesg errors ref  regulators and `mpp_rkvenc2` and `mpp_rkvdec2` and `vop`.  So I'm thinking maybe some board DT nodes need tweaking?

I've quickly tested Jellyfin (10.9.7) and it transcodes `Stream #0:0 -> #0:0 (h264 (h264_rkmpp) -> hevc (hevc_rkmpp))`, possibly with slightly higher CPU usage than I was used to, but I'm unsure.

**Comment by rpardini** [comment]
Tested on NanoPC T6-LTS, after cherry-picking and adapting https://github.com/armbian/linux-rockchip/pull/207.
(Sent https://github.com/amazingfate/linux-rockchip/pull/1 to @amazingfate  against his wip branch for ease-of-mergeness).

- `rkr1`: https://paste.next.armbian.com/eqokiwugul
- `rkr3-wip` + lts DT cherry pick: https://paste.next.armbian.com/lilekuhezo

nvme, usb2 / usb3 / type-c udc, hdmi, etc, all work.

**Review by rpardini — APPROVED** [review]
Can't find any blockers across all the tests I did. I'd say merge! Thanks for the amazing work.

**Pull request merged**
