### PR TITLE
Update Rk 6.1 to rkr4.1

### PR DESCRIPTION
**Pull request by amazingfate**
Dropped commits:
| commit | drop reason |
| --- | --- |
| https://github.com/armbian/linux-rockchip/commit/672dacbd8ad508dac08ef1837f39045f8847ed4a | This commit is reverted by following https://github.com/armbian/linux-rockchip/commit/1b4ed9889d5509abb4346b8368602fd672e298e5 |
| https://github.com/armbian/linux-rockchip/commit/1b4ed9889d5509abb4346b8368602fd672e298e5 |  |
| https://github.com/armbian/linux-rockchip/commit/8dd683ae14090b1632e860bfb4f291c72c1c4b55 | This commit is reverted by following https://github.com/armbian/linux-rockchip/commit/5bfb5b98a9bd1c6f10c4bbf8565a9f5f39775539 |
| https://github.com/armbian/linux-rockchip/commit/5bfb5b98a9bd1c6f10c4bbf8565a9f5f39775539 |  |
| https://github.com/armbian/linux-rockchip/commit/443f54c4d36f09a3a782646dfbb68bc3acbdd581 | I have merged this commit inside https://github.com/amazingfate/linux-rockchip/commit/04b4eb026a2d98a3b3a4489d8d1c7217affbd26e |
| https://github.com/armbian/linux-rockchip/commit/81d767d462a8db3517b01a7d9f8841b8d7450708 | Rockchip has bumped MALI DDK to g24p0, mali firmware is inside kernel, so no need to deal with different version of mali firmwares, and panfork works. ~~lets see if it will break panfork~~ |
| https://github.com/armbian/linux-rockchip/commit/672dacbd8ad508dac08ef1837f39045f8847ed4a | This commit is reverted by following https://github.com/armbian/linux-rockchip/commit/1b4ed9889d5509abb4346b8368602fd672e298e5 |
| https://github.com/armbian/linux-rockchip/commit/1b4ed9889d5509abb4346b8368602fd672e298e5 |  |
| https://github.com/armbian/linux-rockchip/commit/16a7adc42e350ee3ff96298f295ae01f52f103bb | Already in rkr4.1 |

### CODE REVIEW

**Comment by amazingfate** [comment]
Tested jammy with panfork driver, although DDK is bumped to g25p0, panfork can still use mali firmware from g15p0.

**Comment by ginkage** [comment]
On that note, do keep in mind that there's a new flag `MALI_CSF_INCLUDE_FW` (default "yes"), so that g15 firmware may not actually have been used, as the relevant firmware g25 is now embedded into kernel by default.

**Comment by amazingfate** [comment]
> On that note, do keep in mind that there's a new flag `MALI_CSF_INCLUDE_FW` (default "yes"), so that g15 firmware may not actually have been used, as the relevant firmware g25 is now embedded into kernel by default.

That is far better than the old way!

**Comment by HeyMeco** [comment]
> although DDK is bumped to g25p0

@JeffyCN can you update the [libmali mirror](https://github.com/JeffyCN/mirrors/tree/libmali) with the g25p0 userspace driver?

**Comment by ginkage** [comment]
AFAIK there is no g25 userspace driver available...
There is g24 though, and that indeed would be nice to have released.

**Comment by JeffyCN** [comment]
> > although DDK is bumped to g25p0
> 
> @JeffyCN can you update the [libmali mirror](https://github.com/JeffyCN/mirrors/tree/libmali) with the g25p0 userspace driver?

updated to the newest version :)

**Comment by AaronDewes** [comment]
I've been experiencing a kernel panic on boot on an Radxa CM5 with this branch. I'm using a custom kernel config though, as well as a custom carrier board. The custom config fully worked on 6.1-rkr3.

I'll check if I can reproduce the issue with the official carrier board soon, just wanted to let you know that there could be an issue with this branch.

**Comment by ginkage** [comment]
FWIW, this kernel boots perfectly fine on my CM5 with the Radxa I/O board.

**Comment by amazingfate** [comment]
> I've been experiencing a kernel panic on boot on an Radxa CM5 with this branch. I'm using a custom kernel config though, as well as a custom carrier board. The custom config fully worked on 6.1-rkr3.
> 
> I'll check if I can reproduce the issue with the official carrier board soon, just wanted to let you know that there could be an issue with this branch.

what kind if kernel panic, are there logs of it?

**Comment by AaronDewes** [comment]
Just checked again: It was related to undervoltage :sweat_smile:  

Using a different power supply fixed it, apparently mine was faulty.

**Comment by amazingfate** [comment]
Tested with:
- armsom sige1(rk3528)
- armsom sige3(rk3568)
- armsom cm5-io(rk3576)
- armsom sige7(rk3588)
- rock5b(rk3588)

**Comment by HeyMeco** [comment]
Gonna test on these later
- [x] Rock5B+
- [x] Rock5B (doesn’t hurt testing twice)

Both confirmed working with rkr4.1

**Pull request merged**
